### ISSUE TITLE
Error al registrarme

### ISSUE THREAD

**Issue by Wragdan** [Wragdan/chat-api#1]
Intento hacer POST y no devuelve nada y me responde con code 500 internal error

**Comment by RinerJBonilla** [comment]
![screenshot from 2018-02-25 02-53-07](https://user-images.githubusercontent.com/20601938/36642701-313953ee-1a09-11e8-8c8a-eea95be4611a.png)
que raro, mi como creo un usuario en postman

**Comment by RinerJBonilla** [comment]
![screenshot from 2018-02-25 02-55-11](https://user-images.githubusercontent.com/20601938/36642732-67c41a02-1a09-11e8-9099-f5d68a4b94b0.png)
el login con el token creado

**Comment by RinerJBonilla** [comment]
![screenshot from 2018-02-25 02-59-42](https://user-images.githubusercontent.com/20601938/36642788-0f3c0a60-1a0a-11e8-8b9f-351467b9d7ab.png)
prueba del token

**Comment by RinerJBonilla** [comment]
![screenshot from 2018-02-25 03-14-50](https://user-images.githubusercontent.com/20601938/36643037-255a4436-1a0c-11e8-8675-e79195863989.png)
crear conversation

**Comment by RinerJBonilla** [comment]
![screenshot from 2018-02-25 03-15-58](https://user-images.githubusercontent.com/20601938/36643062-5098f3ea-1a0c-11e8-84a8-0eb0e0beb7bc.png)
listar conversations

**Comment by RinerJBonilla** [comment]
![screenshot from 2018-02-25 03-17-13](https://user-images.githubusercontent.com/20601938/36643082-7991b98a-1a0c-11e8-8ca5-80ff897c8895.png)
listar users

**Comment by RinerJBonilla** [comment]
![screenshot from 2018-02-25 03-37-21](https://user-images.githubusercontent.com/20601938/36643318-524541aa-1a0f-11e8-9c49-79223ecbdd6d.png)
crear mensaje

**Comment by RinerJBonilla** [comment]
![screenshot from 2018-02-25 03-38-44](https://user-images.githubusercontent.com/20601938/36643337-7995f344-1a0f-11e8-893e-cbad2fe05e34.png)
listar mensaje

**Comment by RinerJBonilla** [comment]
![screenshot from 2018-02-25 03-48-30](https://user-images.githubusercontent.com/20601938/36643438-d57c17aa-1a10-11e8-96d2-1bb3a0cf5e2b.png)
mensajes de la conversacion, visto desde el otro usuario(recipient)

**Comment by Wragdan** [comment]
Buenas, sigue teniendo el mismo error... le recuerdo que para registrarme no necesito autorizacion
ya que la autorization token se consigue en login.. es decir, no hay manera de registrarme en la aplicacion.

**Comment by Wragdan** [comment]
Podrias probar haciendo lo mismo que haces en registro (con todo y token) pero en la api subida en heroku.. probablemente no hayas hecho los migrate.

**Comment by RinerJBonilla** [comment]
Estas usando solo el heroku? porque en esta branch ya esta acualizado la confirmacion,
la linea "skip_before_action :authenticate_request, only: %i[login register]" especifica que para acceder a cualquier ruta, verifica si existe el token que solo login lo crea, solo las rutas POST auth/register y auth/login no piden dicho token.
PD: no tengo ruta root ya que las unicas dos que no piden token son tipo POST, asi que agarra las ruta GET /test, pero esa pide token, por eso asumiria que el main page de la API te salga un error de missing token, lo que puedo hacer es un placeholder GET como root
