### ISSUE TITLE
Datos dificiles de obtener

### ISSUE THREAD

**Issue by Wragdan** [Wragdan/chat-api#3]
Cuando dejo un campo vacio en auth/register, deberia de dar el error de la siguiente manera

```javascript
{
   "message": "Favor rellenar todos los datos"
}
```
y ya, no necesitas una propiedad extra por cada campo vacio.

**Comment by RinerJBonilla** [comment]
![screenshot from 2018-02-25 18-35-28](https://user-images.githubusercontent.com/20601938/36657172-3220dbf0-1a91-11e8-8886-419104e8696f.png)
ahora verfica que los params no este vacios en todos los POST

**Comment by Wragdan** [comment]
Recordar que los cambios deben estar siendo actualizados en heroku tambien, ya que de alli obtengo mis datos, no lo trabajo local.

**Comment by RinerJBonilla** [comment]
listo
