### ISSUE TITLE
Las tokens tienen fecha de vencimiento

### ISSUE THREAD

**Issue by Wragdan** [Wragdan/chat-api#4]
Por favor hacer que no venzan, ya que toca iniciar sesion de nuevo.

**Comment by RinerJBonilla** [comment]
![screenshot from 2018-02-26 02-35-29](https://user-images.githubusercontent.com/20601938/36675908-e165f094-1acf-11e8-9536-2d75da0d97d0.png)
ya deberia de durar para siempre el token, le quite expiration date

**Comment by Wragdan** [comment]
Gracias
