### ISSUE TITLE
Mal nombre para password

### ISSUE THREAD

**Issue by Wragdan** [Wragdan/chat-api#5]
Por favor hacer que al registrarte, el campo de contraseña se llame *password* en lugar de *password_digest*.

**Comment by RinerJBonilla** [comment]
a que te refieres? internamente el parametro se llama _password_digest_ para que bcrypt la la reconozca y la encripte pero, en postman solo debes pone _password_ y la relaciona con la columna interna, porque en la base de datos se llama _password_digest_
